name = "reacttemplate"
compatibility_date = "2024-03-29"

# Configuración de Pages
pages_build_output_dir = "dist"

# Entorno de producción
[env.production]

# Entorno de vista previa (el único otro ambiente soportado por Pages)
[env.preview] 