name = "reacttemplate-api"
main = "src/index.ts"
compatibility_date = "2024-03-29"

[vars]
# Variables de entorno que quieras definir para tu Worker
# API_KEY = "..."

# Configuración para desarrollo local
[dev]
port = 8787
local_protocol = "http"

# Configuración para producción
routes = [
  { pattern = "api.reacttemplate.pages.dev", zone_name = "pages.dev" }
]

# Configuración para compilación - TypeScript
[build]
command = "npm run build" 