name = "reacttemplate-api"
main = "src/index.ts"
compatibility_date = "2024-03-29"

# Configuración para desarrollo local
[dev]
port = 8787
local_protocol = "http"

# Configuración de dominio personalizado
# Para workers asociados a Pages, es mejor usar custom_domain
# https://developers.cloudflare.com/workers/configuration/routing/custom-domains/
custom_domain = "api.reacttemplate.pages.dev"

# Configuración para compilación - TypeScript está gestionado por Workers
[build]
command = "npm run build" 