name: Deploy to Cloudflare Pages and Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
        
      - name: Install Worker dependencies
        run: cd workers-api && npm install
      
      - name: Build project
        run: npm run build
        
      - name: Build Worker
        run: npm run build:worker
      
      - name: Check if Cloudflare Pages project exists
        id: check_project
        run: |
          # Intentar obtener info del proyecto para ver si existe
          PROJECT_EXISTS=$(npx wrangler pages project list | grep -c "reacttemplate" || echo "0")
          echo "project_exists=$PROJECT_EXISTS" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      
      - name: Create Cloudflare Pages project if needed
        if: steps.check_project.outputs.project_exists == '0'
        run: |
          npx wrangler pages project create reacttemplate --production-branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      
      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=reacttemplate --commit-dirty=true --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          
      - name: Update Wrangler to latest version
        run: |
          cd workers-api
          npm install wrangler@latest
      
      - name: Deploy to Cloudflare Workers
        run: |
          cd workers-api
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }} 