name: Deploy to Cloudflare Pages and Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
        
      - name: Install Worker dependencies
        run: cd workers-api && npm install
      
      - name: Build project
        run: npm run build
        
      - name: Build Worker
        run: npm run build:worker
      
      - name: Create Cloudflare Pages project if not exists
        run: |
          # Intentar crear el proyecto (si ya existe, fallará pero no detendrá el workflow)
          npx wrangler pages project create reacttemplate --production-branch=main || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      
      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=reacttemplate --commit-dirty=true --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'workers-api'
          command: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }} 